AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  geocrosswalk:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: 'arn:aws:iam::794591657841:role/service-role/testrole'
      Runtime: nodejs6.10
      Timeout: 3
